### ISSUE TITLE
Help run

### ISSUE THREAD

**Issue by sayajinpt** [nicholashc/AtomicArbBot#2]
Hello , in time i was writing the same thing as ir bot but on Python , i came across ur project. Im not in deep with Smart contracts or solidity works, can u write a Simple Tut how o Run this ,and with what. If que got a oportunity and the bot create the trade , to were the profit goes? I cant find in code were to specify  account, and last, i see it is pointing to localhost. Can i point it to infura mainnet? 

Sorry for so much trouble and questions, have a nice day mate .

**Comment by nicholashc** [comment]
I am not actively supporting this project. You are free to use and/or modify the code as you wish but it is provided as is.
